name: Build Android
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-path: app/package-lock.json

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # or 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: app
        run: npm install

      - name: Build Android AAB (Free Local Build)
        working-directory: app
        env:
          JAVA_HOME: /usr/lib/jvm/zulu-17-ca-amd64 # actions/setup-java sets this automatically, but being explicit helps
        run: |
          npx eas-cli build --platform android --profile production --local --non-interactive --output=./uljip_check_v2.aab

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app-bundle
          path: app/uljip_check_v2.aab
